name: webserver

services:
 webserver:
    image: 'httpd:2.4'
    container_name: webserver
    restart: unless-stopped
    volumes:
      - ./data:/usr/local/apache2/htdocs/
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webserver.rule=(Host(`${TRAEFIK_WEBSERVER}`) || Host(`${TRAEFIK_WEBSERVER_ALT}`))"
      - "traefik.http.routers.webserver.entrypoints=https"
      - "traefik.http.routers.webserver.tls=true"
      - "traefik.http.routers.webserver.tls.certresolver=mytlschallenge"
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"

networks:
   proxy:
    external: true
