services:
  radicale:
    image: xlrl/radicale:latest
    container_name: radicale
    restart: unless-stopped
    environment:
      RADICALE_USER: ${USERNAME}
      RADICALE_PASS: ${PASSWORD}
    volumes:
      - ./data:/var/radicale
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radicale.rule=Host(`${TRAEFIK_RADICALE}`)"
      - "traefik.http.routers.radicale.entrypoints=https"
      - "traefik.http.routers.radicale.tls=true"
      - "traefik.http.routers.radicale.tls.certresolver=mytlschallenge"
      # Watchtower Update
      - "com.centurylinklabs.watchtower.enable=true"

networks:
   proxy:
    external: true