http:
  middlewares:
    whitelist:
      ipAllowList:
        sourceRange:
          - "0.0.0.0/0"
          # Private IP range use by docker, enable to enable services access through VPN
          #- "172.16.0.0/12"